##
# Developed by Bobby Earl and Trip Ottinger
# January 2015
#
# Many resources already exist for generating, creating, and updating this site.
# The README.md and /admin/ locations are both great starts.
#
# NOTES:
#   - Please be mindful of leading and trailing slashes.  Mirror the current structure used.
#   - Unfortunately yaml doesn't have a mechanism to concat variables / strings.
#   - This means be very mindful that you may have to update URL's in a few places, ie variables and the links section.
##

# Used to correctly link in different environments
baseurl: /developer.blackbaud.com-renxt
url: http://developer.blackbaud.com
permalink: /resources/blog/home/:year/:month/:day/:title/

# Blog setup
paginate: 3 # Purposefully low just to show pagination
paginate_path: /resources/blog/home/:num

# Used as the base in the feedback section
githubbase: https://github.com/blackbaud-community
githubblob: https://github.com/blackbaud-community/developer.blackbaud.com-renxt/blob/gh-pages

# Custom Site Variables
title: RENXT Developer Portal - Prototype
productname: RE NXT
devportalname: API management developer portal
authorizationservicename:  Blackbaud Authorization Service
authenticatioservicenname:  Blackbaud Authorization Service
devportalurl: https://bbapidev.portal.azure-api.net
devportalurlsubscribeproduct: https://bbapidev.portal.azure-api.net/products
communityurl: http://blackbaud.smallworldlabs.com
communitygroupurl:  http://blackbaud.smallworldlabs.com/groups/home/30
communityblogurl:  http://blackbaud.smallworldlabs.com/groups/blogs/30
communityforumurl: http://blackbaud.smallworldlabs.com/groups/forums/29/85

# This block sets some default page variables
defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"
      showComments: false
      showFeedback: false
      showSidebar: true
      showHeadings: true
      sidebarRelative: false
      sidebar: ""
  - 
    scope:
      type: "posts"
    values:
      layout: "post"
      showComments: true

# NOTE: For consistency and performance, please begin and end all internal site URL's with a forward slash.
links:
  - name: Home
    url: /
    
  - name: Tutorials
    url: /tutorials/
    links:
    
      - name: Getting Started
        url: /tutorials/getting-started/
        description: "This tutorial introduces our developer portal, developer sign up process, technical reference, and interactive API Console."
    
      - name: Web API Authorization
        url: /tutorials/auth/
        description: "This tutorial shows you how to create a small server-side application that accesses user-related data through the RE NXT API."
    
      - name: Search and Retrieve a Constituent
        url: '#'
        description:
    
      - name: Common Developer Use Case Tutorial 1
        url: '#'
        description:
    
      - name: Another Common Use Case Tutorial 2
        url: '#'
        description:
    
  - name: Developer Guide
    url: /guide/
      
  - name: Resources
    url: /resources/
    links:
        
      - name: Blog
        url: /resources/blog/
        
      - name: Forum
        url: /resources/forum/
        
      - name: FAQ
        url: /resources/faq/
        
      - name: My Applications
        url: /resources/applications/
        
      - name: Analytics
        url: https://bbapidev.portal.azure-api.net/developer/analytics/
        
      - name: Status
        url: /resources/status/
        
      - name: Issues
        url: /resources/issues/
        
      - name: Change Log
        url: /resources/changelog/
        
      - name: Code Samples
        url: /resources/code/
        
  - name: Developer Portal
    url: https://bbapidev.portal.azure-api.net
        
  - name: Legal
    url: /legal/
    showInHeader: false
