title: RENXT Developer Portal - Prototype
baseurl: /developer.blackbaud.com-renxt/
url: http://developer.blackbaud.com
communityurl: http://blackbaud.smallworldlabs.com
communitygroupurl:  http://blackbaud.smallworldlabs.com/groups/home/30
communityblogurl:  http://blackbaud.smallworldlabs.com/groups/blogs/30
productname: RE NXT
devportalname: API management developer portal
# This entire block simply sets the default layout.
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      sidebarRelative: true
      sidebar: ""

# NOTE: For consistency and performance, please begin and end all internal site URL's with a forward slash.
links:
  - name: Home
    url: /
    
  - name: Tutorials
    url: /tutorials/
    links:
    
      - name: Getting Started
        url: /tutorials/getting-started/
    
      - name: Web API Authorization
        url: '/tutorials/auth/'
    
      - name: Registering Your App
        url: '/tutorials/registerapp/'
    
      - name: Searching and Retrieving a Constituent
        url: '#'
    
      - name: Common Developer Use Case Tutorial 1
        url: '#'
    
      - name: Another Common Use Case Tutorial 2
        url: '#'
    
  - name: Developer Guide
    url: /guide/
    links:
    
      - name: Schema
        url: '#'
        
      - name: Parameters
        url: '#'
        
      - name: Version
        url: '#'
        
      - name: Pagination
        url: '#'
        
      - name: Rate Limiting
        url: '#'
        
      - name: Quota
        url: '#'
        
      - name: Endpoints (Create blended content from azure management API & authored content, with links back to azure technical reference)
        url: '#'
        
      - name: ...
        url: '#'
      
  - name: Resources
    url: /resources/
    links:
    
      - name: Developer Portal
        url: '#'
        
      - name: Issues (Option 1 SWL, Option 2 Jekyll)
        url: '#'
        
      - name: Developer Blog (Option 1 SWL, Option 2 Jekyll)
        url: '#'
        
      - name: Keep In Touch
        url: '#'
        
      - name: Code Samples
        url: '#'
        
      - name: Change Log
        url: /changelog/
      
  - name: Support
    url: /support/
    links:
    
      - name: FAQ
        url: '#'
        
      - name: Forum
        url: '#'
        
      - name: API Status
        url: '#'
        
      - name: Report an Issue (Option 1 Azure, Option 2 Contact Us with subject prefilled)
        url: '#'
        
      - name: Issues Blog (Option 1 SWL, Option 2 Jekyll)
        url: '#'