# =============================================
# Build config
# =============================================

appSrc: 'app-src/'
appDist: 'app-dist/'
appData: '<%= paths.appSrc %>_data/'
portalName: 'bbapidev'
portalApi: 'https://<%= paths.portalName %>.management.azure-api.net'
#portalQueryString: {
#  'api-version': '2014-02-14-preview'
#}
nuget: 'Blackbaud.SkyUI.Sass'
nugetDir: '_nuget/<%= paths.nuget %>'
nugetServer: 'http://tfs-sym.blackbaud.com:81/nuget/'
nugetVersion: ''  # Set by blackbaud:skyui-nuget
skyJsonRemote: '' # Set by blackbaud:skyui-nuget
skyJsonRemoteById: '<%= paths.nugetServer %>FindPackagesById()?id=\'<%= paths.nuget %>\'&$orderby=Published desc&$top=1'
skyJsonRemoteByVersion: '<%= paths.nugetServer %>Packages(Id=\'<%= paths.nuget %>\',Version=\'<%= paths.nugetVersion %>\')'
skyTfsLocal: '_sass/Sky/'
skyTfsRemote: '$/Products/REx/Styles/Sky/DEV/Sky/Content/Styles/Sky/'
skyZipExpanded: '<%= paths.nugetDir %>/'
skyZipLocal: '<%+ paths.nugetDir %>.zip'
skyZipRemote: '' # Set by http:skyui-json
tfs:  'https://tfs.blackbaud.com/tfs/DefaultCollection/'