# Used to correctly link in different environments
baseurl: /developer.blackbaud.com-renxt/
url: http://developer.blackbaud.com
permalink: /resources/blog/:categories/:year/:month/:day/:title/

# Blog setup
paginate: 10
paginate_path: /resources/blog/page:num

# Used as the base in the feedback section
github: https://github.com/blackbaud-community/developer.blackbaud.com-renxt/blob/gh-pages

# Custom Site Variables
title: RENXT Developer Portal - Prototype
productname: RE NXT
devportalname: API management developer portal
authservicename:  Blackbaud OAuth 2.0 Service
devportalurl: https://bbbobbyearl.portal.azure-api.net/
devportalurlsubscribeproduct: https://bbbobbyearl.portal.azure-api.net/products
communityurl: http://blackbaud.smallworldlabs.com
communitygroupurl:  http://blackbaud.smallworldlabs.com/groups/home/30
communityblogurl:  http://blackbaud.smallworldlabs.com/groups/blogs/30

# This block sets some default page variables
defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"
      showComments: false
      showFeedback: false
      showSidebar: true
      showHeadings: true
      sidebarRelative: false
      sidebar: ""
  - 
    scope:
      type: "posts"
    values:
      layout: "post"
      showComments: true

# NOTE: For consistency and performance, please begin and end all internal site URL's with a forward slash.
links:
  - name: Home
    url: /
    
  - name: Tutorials
    url: /tutorials/
    links:
    
      - name: Getting Started
        url: /tutorials/getting-started/
    
      - name: Web API Authorization
        url: /tutorials/auth/
    
      - name: Registering Your App
        url: /tutorials/register-app/
    
      - name: Searching and Retrieving a Constituent
        url: '#'
    
      - name: Common Developer Use Case Tutorial 1
        url: '#'
    
      - name: Another Common Use Case Tutorial 2
        url: '#'
    
  - name: Developer Guide
    url: /guide/
      
  - name: Resources
    url: /resources/
    links:
    
      - name: Developer Portal
        url: https://bbbobbyearl.portal.azure-api.net/
        
      - name: Developer Blog
        url: /resources/blog/
        
      - name: Community
        url: /resources/community/
        
      - name: FAQ
        url: /resources/faq/
        
      - name: Status
        url: /resources/status/
        
      - name: Issues
        url: /resources/issues/
        
      - name: Change Log
        url: /resources/changelog/
        
      - name: Code Samples
        url: /resources/code/
        
  - name: Legal
    url: /legal/
    header: false