title: RENXT Developer Portal - Prototype
baseurl: /developer.blackbaud.com-renxt/
url: http://developer.blackbaud.com

# This entire block simply sets the default layout.
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      sidebarRelative: true
      sidebar: ""

# NOTE: For consistency and performance, please begin and end all internal site URL's with a forward slash.
links:
  - name: Home
    url: /
    
  - name: Getting Started
    url: /start/
    links:
    
      - name: Welcome
        url: '#'
        
      - name: Authentication
        url: '#'
    
  - name: Tutorials
    url: /tutorials/
    links:
        
      - name: Authentication (Use Case 1)
        url: '#'
        
      - name: Searching for a Constituent (Use Case 2)
        url: '#'
        
      - name: Updating Constituent Address (Use Case 3)
        url: '#'
        
      - name: Another Common Tutorial (Use Case ...)
        url: '#'
      
  - name: Developer Guide
    url: /guide/
    links:
    
      - name: Schema
        url: '#'
        
      - name: Parameters
        url: '#'
        
      - name: Version
        url: '#'
        
      - name: Pagination
        url: '#'
        
      - name: Rate Limiting
        url: '#'
        
      - name: Quota
        url: '#'
        
      - name: Endpoints (Create blended content from azure management API & authored content, with links back to azure technical reference)
        url: '#'
        
      - name: ...
        url: '#'
      
  - name: Resources
    url: /resources/
    links:
    
      - name: Developer Portal
        url: '#'
        
      - name: Issues (Option 1 SWL, Option 2 Jekyll)
        url: '#'
        
      - name: Developer Blog (Option 1 SWL, Option 2 Jekyll)
        url: '#'
        
      - name: Keep In Touch
        url: '#'
        
      - name: Code Samples
        url: '#'
        
      - name: Libraries
        url: '#'
        
      - name: Change Log
        url: /changelog/
      
  - name: Support
    url: /support/
    links:
    
      - name: FAQ
        url: '#'
        
      - name: Forum
        url: '#'
        
      - name: API Status
        url: '#'
        
      - name: Report an Issue (Option 1 Azure, Option 2 Contact Us with subject prefilled)
        url: '#'
        
      - name: Issues Blog (Option 1 SWL, Option 2 Jekyll)
        url: '#'