##
# Developed by Bobby Earl and Trip Ottinger
# January 2015
#
# Many resources already exist for generating, creating, and updating this site.
# The README.md and /admin/ locations are both great starts.
#
# NOTES:
#   - Please be mindful of leading and trailing slashes.  Mirror the current structure used.
#   - Unfortunately yaml doesn't have a mechanism to concat variables / strings.
#   - This means be very mindful that you may have to update URL's in a few places, ie variables and the links section.
##

# Jekyll configurations
exclude:
  - package.json
  - gruntfile.js
  - node_modules
  - README.md
sass:
  style: compressed
  
# This defaults to work on github pages.
# It should be overwritten for all over environments.
baseurl: /developer.blackbaud.com-renxt

# URL's throughout the site
url: http://developer.blackbaud.com
githubbase: https://github.com/blackbaud-community
githubblob: https://github.com/blackbaud-community/developer.blackbaud.com-renxt/blob/gh-pages

# This block sets some default page variables
defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"
      showComments: false
      showFeedback: false
      showSidebar: true
      showHeadings: true
      sidebarRelative: false
      sidebar: ""
